<a href="https://colab.research.google.com/github/sid-sank/Computational-Statistics/blob/main/Class_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("wsg")

wsg


# Markdown cheat sheet

- Bulleted list
1. Numbered list

~Strike through~

`Code`

_Italics_ or *Italics*

**Bold**

# Heading one

## Heading two

### Heading three

# Data Types


In [36]:
# Pyhon does not require type declaration

"""
Python allows
multiline
comments
"""

a = 5 # Int
var = 10.0 # Float (has finite precision, may lead to floating point errors?)
myStr = "Alex" # String
print(f"a is a var of type {type(a)}")
type(myStr)
myFloat = a + var # Adding a float and an int gives a float
myBool = True
notMyBool = not myBool
print(notMyBool)

a is a var of type <class 'int'>
False


# Operators

In [19]:
a = 1
b = 3

p = a + b # Addition
q = a - b # Subtraction
r = a * b # Multiplication
s = a / b # Division

print(p, q, r, s)

t = a // b # Rounded division
u = a % b  # Modulo (reminder)
v = a ^ b  #Bitwise XOR (11 ^ 01 = 10)

print (t, u, v)
print("s is ", s)
print(f"the sum of '{a}' and '{b}' is {p}")

4 -2 3 0.3333333333333333
0 1 2
s is  0.3333333333333333
the sum of '1' and '3' is 4


# Lists and Arrays


In [26]:
int_list = [1, 2, 3, 4]
float_list  =  [float(i) for i in int_list] # Called list comprehension
print(int_list)
print(float_list)
mixed_list = [1, 2.3, "r", r, True] # Allows for multiple datatypes, but may break certain functions if not used carefully
mixed_list

[1, 2, 3, 4]
[1.0, 2.0, 3.0, 4.0]


[1, 2.3, 'r', 3]

# List operations

In [44]:
scores = [65, 78, 90, 85]
print(f"Class average: {sum(scores)/ len(scores)}") #Breaks for mixed strings
print(f"Higest score: {max(scores)}, Lowest score: {min(scores)}")

mixed_list = int_list + float_list
print(mixed_list) # + concatenates lists
print(sum(mixed_list)) # Only breaks with strings

Class average: 79.5
Higest score: 90
Lowest score: 65
[1, 2, 3, 4, 1.0, 2.0, 3.0, 4.0]
20.0


# Functions and control operations


In [52]:
def has_passed(int): # Local and global var names allow this
  if int > 80: # This int var is local you cannot call it outside this function
    return True
  else: return False

Pass_TF = [has_passed(i) for i in scores] # Called list comprehension - new way

for i in scores: # Old python way
  print(f"student #{scores.index(i) + 1}: {has_passed(i)}")

def TF_to_SU(bool):
  if bool: return "Satisfactory"
  else: return "Unsatisfactory"
SU = [TF_to_SU(i) for i in Pass_TF]
print(SU)

student #1: False
student #2: False
student #3: True
student #4: True
['Unsatisfactory', 'Unsatisfactory', 'Satisfactory', 'Satisfactory']


# Match statements

In [63]:
def get_grades(int):
  match int:
    case int if int < 40:
      return "U"
    case int if 40 <= int < 50:
      return "E"
    case int if 50 <= int < 60:
      return "D"
    case int if 60 <= int < 70:
      return "C"
    case int if 70 <= int < 80:
      return "B"
    case int if 80 <= int < 90:
      return "A-"
    case int if 90 <= int < 95:
      return "A"
    case int if 95 <= int :
      return "O"
grades = [ get_grades(i) for i in scores]
print(grades)


['C', 'B', 'A', 'A-']


# Dictionaries

In [74]:
names = ["Alex", "Nandini", "Mohamad", "Raju"]
scores_dict = {names[i]:scores[i] for i in range(len(scores))} # Comprehension works here also
scores_dict

{'Alex': 65, 'Nandini': 78, 'Mohamad': 90, 'Raju': 85}

# Homework
- Use the dict to print student names and scores
- Print along with grades

In [84]:
for name, score in scores_dict.items(): # Extract items as a list of tuples
  print(f"Student name: {name}, score: {score}")

print("\nAlternate method \n" )

for name in scores_dict.keys(): # Extract keys as a list and use that to acesss the key pair values
  print(f"Student name: {name}, score: {scores_dict[name]}")

Student name: Alex, score: 65
Student name: Nandini, score: 78
Student name: Mohamad, score: 90
Student name: Raju, score: 85

Alternate method 

Student name: Alex, score: 65
Student name: Nandini, score: 78
Student name: Mohamad, score: 90
Student name: Raju, score: 85


# NUMPY

In [85]:
import numpy as np

In [96]:
zeros_arr = np.zeros(10) #An array of zero value floats
print(zeros_arr)
ones_arr_2d_int = np.ones((5,5), int)
print(ones_arr_2d_int)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# Array operations


In [99]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
print(f"First array is {arr1}, second array is {arr2}")
print(f"They are both of type {type(arr1)}, not a regular list")

First array is [1 2 3 4 5], second array is [ 6  7  8  9 10]
They are both of type <class 'numpy.ndarray'>, not a regular list


In [101]:
sum_arr = arr1 + arr2 # Elementwise addition
sub_arr = arr1 - arr2 # Elementwise subtraction
mul_arr = arr1 * arr2 # Elementwise multiplication
div_arr = arr1 / arr2 # Elementwise division

print(sum_arr, sub_arr, mul_arr, div_arr)

[ 7  9 11 13 15] [-5 -5 -5 -5 -5] [ 6 14 24 36 50] [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


# More Homework
- Checkout pandas
- Advanced operations in linear algerbra with numpy
